services:
  db:
    image: postgres:16.3-alpine3.20
    container_name: db
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
